# Generated by Django 5.2.4 on 2025-07-24 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(default='Default department description. Please update.', help_text='A comprehensive description of the department and its main focus.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing the department.', null=True, upload_to='department_images/'),
        ),
        migrations.CreateModel(
            name='DepartmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Brief description of this specific service.')),
                ('icon_class', models.CharField(help_text='e.g., flaticon-stethoscope, flaticon-flask', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='medical.department')),
            ],
        ),
    ]
