# Generated by Django 5.2.4 on 2025-07-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_appointment_unique_together_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
